openapi: 3.0.1
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  termsOfService: http://swagger.io/terms/
  version: 1.0.0
servers:
- url: http://localhost:3001/api/v1
paths:
  /user/login:
    post:
      tags:
      - User Module
      summary: Login
      description: API for Login
      requestBody:
        description: Login Payload
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/Login'
        required: true
      responses:
        200:
          description: Login Successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        400:
          description: Invalid Fields
          content: {}
        500:
          description: Internal Server Error
          content: {}
      x-codegen-request-body-name: body
  /user/signup:
    post:
      tags:
      - User Module
      summary: Signup
      description: API for Signup
      requestBody:
        description: Signup Payload
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        200:
          description: Signup Successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        400:
          description: Invalid Fields
          content: {}
        500:
          description: Internal Server Error
          content: {}
      x-codegen-request-body-name: body
  /user/profile:
    put:
      tags:
      - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
      - name: Authorization
        in: header
        description: Attach Bearer JWT token
        required: true
        schema: {}
      requestBody:
        description: Update user profile attributes
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/UserProfile'
        required: true
      responses:
        200:
          description: User profile retrieved successully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        400:
          description: Invalid Fields
          content: {}
        500:
          description: Internal Server Error
          content: {}
      security:
      - Bearer: []
      x-codegen-request-body-name: body
    post:
      tags:
      - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
      - name: Authorization
        in: header
        description: Attach Bearer JWT token
        required: true
        schema: {}
      responses:
        200:
          description: User profile retrieved successully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        400:
          description: Invalid Fields
          content: {}
        500:
          description: Internal Server Error
          content: {}
      security:
      - Bearer: []
  /user/transaction:
    get:
      tags:
      - User Transaction Module
      summary: User Transaction
      description: API for fetching a user transaction pour le mois en cours
      parameters:
      - name: Authorization
        in: header
        description: Attach Bearer JWT token
        required: true
        schema: {}
      responses:
        200:
          description: User transaction retrieved successully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserTransactionsResponse'
        400:
          description: Request failed
          content: {}
        500:
          description: Internal Server Error
          content: {}
    post:
      tags:
      - User Transaction Module
      summary: Create a transaction
      description: API for create transaction
      parameters:
      - name: Authorization
        in: header
        description: Attach Bearer JWT token
        required: true
        schema: {}
      requestBody:
        description: create one transaction
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/transaction'
        required: true
      responses:
        200:
          description: transaction create successully 
          content: {}
        400:
          description: Request failed
          content: {}
        500:
          description: Internal Server Error
          content: {}
      security:
      - Bearer: []
  /user/transaction/{transcationId}:
    get:
      tags:
      - User Transaction Module
      summary: Get a transaction detail
      description: API for get one transaction
      parameters:
        - name: transcationId
          in: path
          description: transcation id in path
          required: true
          schema: {}
        - name: Authorization
          in: header
          description: Attach Bearer JWT token
          required: true
          schema: {}
      responses:
        200:
          description: transaction retrieved successully 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/transactionDetail'
        400:
          description: Request failed
          content: {}
        404:
          description: transaction id not found
          content: {}
        500:
          description: Internal Server Error
          content: {}
    put:
      tags:
      - User Transaction Module
      summary: Update a transaction
      description: API for updating a transaction
      parameters:
        - name: transcationId
          in: path
          description: transcation id in path
          required: true
          schema: {}
        - name: Authorization
          in: header
          description: Attach Bearer JWT token
          required: true
          schema: {}
      requestBody:
        description: Update transaction
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/transactionDetail'
        required: true
      responses:
        200:
          description: transaction update successully 
          content:
           {}
        400:
          description: Request failed
          content: {}
        404:
          description: transaction id not found
          content: {}
        500:
          description: Internal Server Error
          content: {}
      security:
      - Bearer: []
    delete:
      tags:
      -  User Transaction Module
      summary: Delete a transaction
      description: API for deleting a transaction
      parameters:
        - name: transcationId
          in: path
          description: transcation id in path
          required: true
          schema: {}
        - name: Authorization
          in: header
          description: Attach Bearer JWT token
          required: true
          schema: {}
      responses:
        200:
          description: transaction delete successully 
          content: {}
        400:
          description: Request failed
          content: {}
        404:
          description: transaction id not found
          content: {}
        500:
          description: Internal Server Error
          content: {}
      security:
      - Bearer: []
components:
  schemas:
    User:
      type: object
      properties:
        email:
          type: string
          description: user email
        password:
          type: string
          description: user password
        firstName:
          type: string
          description: user first name
        lastName:
          type: string
          description: user last name
    Login:
      type: object
      properties:
        email:
          type: string
          description: user email
        password:
          type: string
          description: user password
    ApiResponse:
      type: object
      properties:
        status:
          type: integer
        message:
          type: string
        body:
          type: object
          properties:
            id:
              type: string
            email:
              type: string
    LoginResponse:
      type: object
      properties:
        token:
          type: string
    UserProfile:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
    UserTransactionsResponse:
      type: object
      properties:
        status:
          type: integer
        message:
          type: string
        body:
          type: object
          properties:
            id:
              type: string
            email:
              type: string
            transactions:
              type: object
              properties:
                transactionId:
                   type: string
                date:
                   type: string
                description:
                   type: string
                montant:
                   type: number
                balance:
                   type: number
    transaction:
      type: object
      properties:
        transactionId:
          type: string
        transactionDetail:
          type: object
          properties:
            date: 
              type: string
            transactionType:
              type: string
            category:
              type: string
            notes:
              type: string
            description:
              type: string
            montant:
              type: number
            balance:
              type: number
    transactionDetail:
      type: object
      properties:
        date: 
          type: string
        transactionType:
          type: string
        category:
          type: string
        notes:
          type: string
        description:
          type: string
        montant:
          type: number
        balance:
          type: number
  securitySchemes:
    Bearer:
      type: apiKey
      name: Authorization
      in: header
